apiVersion: v1
kind: ResourceQuota 
metadata: 
  name: quota-for-dev
  namespace: dev

spec:   
  hard:
    pods: "10"
    requests.cpu: "4"
    limits.cpu: "10"
    limits.memory: 10Gi                          ## command : kubectl create -f compute-quota.yml