apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]                # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","update","delete"]
  resourceNames: ["blue","orange"]           # if you want to give access to particular pod. Blue and Orange are the names of the pod.
- apiGroups: [""]                # "" indicates the core API group
  resources: ["configMap"]
  verbs: ["create"]              