apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
   - system:authenticated
  usages:
   - digital signature
   - key encipherment
   - server auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTY1U2lxVU1CQnpNT1RDNTBQaTRKeEdEbGdVWmF2cUgzVXRYcnFVZ0hJeHNrCnpZTWFKandta3V0RzBDR2c0Z1YrR29oaldnaThmWVkvN0VEZDhNbU9Ca1k0MXRKaythSk9hRGVSRkRXdTF2b3YKU1NFV0xzL1hrbjF3Z3E5REhBd3JYOG53S0JJaWpGQ0g5Wkl3aHpEUE15OVpZRTF3cUc2NzIrSlgrcUtiL1RJSQppOG9PMk91ZUpHTldGZ25CWVM0NUNrTzVISkE4bnVFSGxTajNwSVk2Qm5tMjJkYUgzZlF4ckJ1R1VzbUFBelhMCmZyZ2JUTmdURzd6SnN0cnJKN2dxWkxOT0pKSTdXUmg3ckpTRGhXNThuaHV5Yk41bUlnQVV5MEhDTE9mZzdONUsKc08vYnRMZXdXdlhzcXdDWk92OTJSTnBWOHlvQ0E0UjlkSnBEZDB1Tm93SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRzJCZkxBSU9XZVZjbGRDbkc0L0IrMFpPQkovK3JJUWNvUDB2TUY5eVJ3bHlNRjl1ajB6CjNpRlFMdzhsMlpCdGx1NUdrNURkeTJmUzRKK1FMOXA0aXNLUldZYmFXQTZ3N3FST1lzUmE4U3pmV2VCbEgrT3oKQk5BcmRjNUVaZzMvWFJ2alh0cHBzNW5jb1laYUZjQnRtTlc2eS9FZlVmL2paU0YxYk56bkJFalpEOWlwbzdIaApqdkVlalZyUEREaVlPak0rYXRDWmprNzh1NVJ4a095TXRacXNiNklVSldSaVVqSXkxd3hNenhBRFVjTndFcG8wCmM5UnRnL3BhTWtEU1dOREN1RXV3czFocE52RXNhT2hGdU1MTzZFYUMrWGVCbGxHMGszajh0bnhlMWl5NktPOHAKL3NUN2hFRUdHZlJHN3dFUmpZQUdKNEdZTDNVWnFQc3NCaGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

###error: error parsing akshay-csr.yaml: error converting YAML to JSON: yaml: line 15: could not find expected ':'
## get request value from cat akshay.csr | base64 | tr -d '\n'