apiVersion: v1
kind: Config
current-context: dev-user@google
clusters:
 - name: my-kube-playground
   cluster:
     certificate-authority: /etc/kubernets/pki/ca.crt   #<PATH to CA certificate> OR you can pass base64 encodeed format for the contents in the file in certificate-authority-data field
     server: https://my-kube-playground:6443
 - name: google                     #same as my-kube-playground
Contexts:
 - name: my-kube-admin@my-kube-playground
   context:
     cluster: my-kube-playground
     user: my-kube-admin
     namespace: finance
users:
 - name: my-kube-admin
   user: 
     client-certificate: admin.crt       #<PATH to User certificate>
     client.key: admin.key               #<PATH to User Key>
 - name: dev-user                        #Same as my-kube-admin