apiVersion: v1
kind: Binding
metadata: 
  name: nginx                   # same as the podName
target:
  apiVersion: v1
  kind: Node
  name: node-01 


  ## To change the node on the running pod , convert the above yml to its equivalent json form and then send 
  ## curl --header "Content-Type:application/json" --request POST --data {"apiVersion":"v1","kind":"Binding","metadata":{"name":"nginx"},"target":{"apiVersion":"v1","kind":"Node","name":"node-01"}}
  ##             http://$SERVER/api/v1/namespaces/default/pods/$PODNAME/binding/