apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-vol1
spec: 
  accessModes: 
    -ReadWriteOnce           # Other options  ReadOnlyMany & ReadWriteMany
  capacity:
    storage: 1Gi
  awsElasticBlockStore: 
    volumeID: <volume-id>
    fsType: ext4
  
  
  
  #hostPath: 
  #  path: /tmp/data