apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage
provisioner: kubernetes.io/gce-pd
parameters:                            #Specific to the provisioner u are using
  type: pd-standard
  replication-type: none