apiVersion: v1
kind: Secret 
metadata: 
  name: app-secret
data: 
  DB_Host: bXlzcWw=                           #echo -n 'mysql' | base64 --> bXlzcWw=     (Ran oN linux env.)
  DB_User: cm9vdA==                           #echo -n 'root' | base64 --> cm9vdA==
  DB_Password: cGFzc3dyZA==                   #echo -n 'passwrd' | base64 --> cGFzc3dyZA==